# app
app_name: GO CRUD RESTfull API
version: 1.0.0
log_file_path: "logs/server.log"
port: ":4444"

# database
db_dialect: mysql
db_name: go_crud_rest_api
db_username: gouser
db_password: gopassword
db_host: localhost
db_port: 3306
db_parameters: "?charset=utf8&parseTime=True&loc=Local"
db_protocol: "tcp"
db_gorm_singular_table": true,
db_gorm_log_mode": false
